/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author medal
 */
public class CREATEQUIZ extends javax.swing.JFrame {

    /**
     * Creates new form CREATEQUIZ
     */
    public CREATEQUIZ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITLE_LABEL_ = new javax.swing.JLabel();
        COURSE_LABEL_ = new javax.swing.JLabel();
        TITLEE_TXTFIELD_ = new javax.swing.JTextField();
        COURSE_TXTFIELD_ = new javax.swing.JTextField();
        DESCRIPTION_LABEL_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DESCRIPTION_TXTAREA_ = new javax.swing.JTextArea();
        NXT_BTN_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREATE QUIZ");

        TITLE_LABEL_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        TITLE_LABEL_.setText("TITLE");

        COURSE_LABEL_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        COURSE_LABEL_.setText("COURSE");

        TITLEE_TXTFIELD_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        TITLEE_TXTFIELD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TITLEE_TXTFIELD_ActionPerformed(evt);
            }
        });

        COURSE_TXTFIELD_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        COURSE_TXTFIELD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COURSE_TXTFIELD_ActionPerformed(evt);
            }
        });

        DESCRIPTION_LABEL_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        DESCRIPTION_LABEL_.setText("DESCRIPTION");

        DESCRIPTION_TXTAREA_.setColumns(20);
        DESCRIPTION_TXTAREA_.setRows(5);
        jScrollPane1.setViewportView(DESCRIPTION_TXTAREA_);

        NXT_BTN_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        NXT_BTN_.setText("NEXT");
        NXT_BTN_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NXT_BTN_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TITLE_LABEL_)
                    .addComponent(COURSE_LABEL_)
                    .addComponent(DESCRIPTION_LABEL_))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(COURSE_TXTFIELD_, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                        .addComponent(TITLEE_TXTFIELD_)))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NXT_BTN_, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(480, 480, 480))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COURSE_LABEL_)
                    .addComponent(COURSE_TXTFIELD_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE_LABEL_)
                    .addComponent(TITLEE_TXTFIELD_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(DESCRIPTION_LABEL_)))
                .addGap(89, 89, 89)
                .addComponent(NXT_BTN_, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TITLEE_TXTFIELD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TITLEE_TXTFIELD_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TITLEE_TXTFIELD_ActionPerformed

    private void COURSE_TXTFIELD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COURSE_TXTFIELD_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COURSE_TXTFIELD_ActionPerformed

    private void NXT_BTN_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NXT_BTN_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NXT_BTN_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREATEQUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREATEQUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREATEQUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREATEQUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CREATEQUIZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COURSE_LABEL_;
    private javax.swing.JTextField COURSE_TXTFIELD_;
    private javax.swing.JLabel DESCRIPTION_LABEL_;
    private javax.swing.JTextArea DESCRIPTION_TXTAREA_;
    private javax.swing.JButton NXT_BTN_;
    private javax.swing.JTextField TITLEE_TXTFIELD_;
    private javax.swing.JLabel TITLE_LABEL_;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
