
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author medal
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        USER_LBL_ = new javax.swing.JLabel();
        PASSWORD_LBL_ = new javax.swing.JLabel();
        USER_TXT_FIELD_ = new javax.swing.JTextField();
        PASSWORD_TXT_FIELD_ = new javax.swing.JPasswordField();
        CLEAR_BTN_ = new javax.swing.JButton();
        LOGIN_BTN_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        USER_LBL_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        USER_LBL_.setText("USERNAME");

        PASSWORD_LBL_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        PASSWORD_LBL_.setText("PASSWORD");

        USER_TXT_FIELD_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        USER_TXT_FIELD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER_TXT_FIELD_ActionPerformed(evt);
            }
        });

        PASSWORD_TXT_FIELD_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N

        CLEAR_BTN_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        CLEAR_BTN_.setText("CLEAR");
        CLEAR_BTN_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR_BTN_ActionPerformed(evt);
            }
        });

        LOGIN_BTN_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        LOGIN_BTN_.setText("LOGIN");
        LOGIN_BTN_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BTN_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PASSWORD_LBL_)
                    .addComponent(USER_LBL_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(USER_TXT_FIELD_)
                    .addComponent(PASSWORD_TXT_FIELD_, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(623, Short.MAX_VALUE)
                .addComponent(CLEAR_BTN_, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(403, 403, 403)
                    .addComponent(LOGIN_BTN_, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(730, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(USER_LBL_)
                    .addComponent(USER_TXT_FIELD_))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PASSWORD_LBL_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PASSWORD_TXT_FIELD_))
                .addGap(27, 27, 27)
                .addComponent(CLEAR_BTN_, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(418, Short.MAX_VALUE)
                    .addComponent(LOGIN_BTN_, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(251, 251, 251)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USER_TXT_FIELD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USER_TXT_FIELD_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USER_TXT_FIELD_ActionPerformed

    private void CLEAR_BTN_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR_BTN_ActionPerformed
        // TODO add your handling code here:
        USER_TXT_FIELD_.setText("");
        PASSWORD_TXT_FIELD_.setText("");
    }//GEN-LAST:event_CLEAR_BTN_ActionPerformed

    private void LOGIN_BTN_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BTN_ActionPerformed
     // Retrieve username and password from text fields
    String username = USER_TXT_FIELD_.getText(); 
    String password = new String(PASSWORD_TXT_FIELD_.getPassword()); // Retrieve password

    String sqlQuery = "SELECT * FROM users WHERE username = ? AND password = ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sqlQuery)) {
        
        stmt.setString(1, username);
        stmt.setString(2, password);

        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            // Login successful, store the username globally
            UserSession.setUsername(username);  // Store username in the UserSession

            System.out.println("Login successful.");

            // Hide the current login window
            this.setVisible(false);

            // Create a new instance of DASHBOARD and show it
            DASHBOARD dashboard = new DASHBOARD();  // Pass the username to the Dashboard (no need to pass it now)
            dashboard.setVisible(true);  // Show the Dashboard
            
        } else {
            // Invalid login
            System.out.println("Invalid username or password.");
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
        }

    } catch (Exception e) {
        // Handle exception (e.g., invalid query, connection issues, etc.)
        System.out.println("An error occurred: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
    }

    }//GEN-LAST:event_LOGIN_BTN_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR_BTN_;
    private javax.swing.JButton LOGIN_BTN_;
    private javax.swing.JLabel PASSWORD_LBL_;
    private javax.swing.JPasswordField PASSWORD_TXT_FIELD_;
    private javax.swing.JLabel USER_LBL_;
    private javax.swing.JTextField USER_TXT_FIELD_;
    // End of variables declaration//GEN-END:variables
}
