/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author medal
 */
public class PROFILE extends javax.swing.JFrame {

    /**
     * Creates new form DASHBOARD
     */
    public PROFILE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        buttonGroup1 = new javax.swing.ButtonGroup();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        PROFILE_BUTTON_ = new javax.swing.JRadioButton();
        DASHBOARD_BUTTON_ = new javax.swing.JRadioButton();
        RESULT_BUTTON_ = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUIZ APP PROFILE");
        setBackground(new java.awt.Color(216, 210, 194));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        buttonGroup1.add(PROFILE_BUTTON_);
        PROFILE_BUTTON_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        PROFILE_BUTTON_.setText("Profile");
        PROFILE_BUTTON_.setActionCommand("Dashboard");
        PROFILE_BUTTON_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROFILE_BUTTON_ActionPerformed(evt);
            }
        });

        buttonGroup1.add(DASHBOARD_BUTTON_);
        DASHBOARD_BUTTON_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        DASHBOARD_BUTTON_.setText("Dashboard");
        DASHBOARD_BUTTON_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DASHBOARD_BUTTON_ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RESULT_BUTTON_);
        RESULT_BUTTON_.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        RESULT_BUTTON_.setText("Result");
        RESULT_BUTTON_.setActionCommand("Dashboard");
        RESULT_BUTTON_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULT_BUTTON_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DASHBOARD_BUTTON_)
                    .addComponent(PROFILE_BUTTON_))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(RESULT_BUTTON_)
                .addGap(115, 115, 115)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1040, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(DASHBOARD_BUTTON_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PROFILE_BUTTON_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RESULT_BUTTON_)
                .addGap(0, 549, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PROFILE_BUTTON_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROFILE_BUTTON_ActionPerformed
    // Open PROFILE
    PROFILE profile = new PROFILE(); // Create an instance of DASHBOARD
    profile.setVisible(true);        // Make it visible
    this.dispose();                  // Close the current frame (optional)

    }//GEN-LAST:event_PROFILE_BUTTON_ActionPerformed

    private void DASHBOARD_BUTTON_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DASHBOARD_BUTTON_ActionPerformed
    // Open DASHBOARD
    DASHBOARD dashboard = new DASHBOARD(); // Create an instance of DASHBOARD
    dashboard.setVisible(true);            // Make it visible
    this.dispose();                        // Close the current frame (optional)
    }//GEN-LAST:event_DASHBOARD_BUTTON_ActionPerformed

    private void RESULT_BUTTON_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULT_BUTTON_ActionPerformed
    // Open RESULT
    RESULT result = new RESULT(); // Create an instance of DASHBOARD
    result.setVisible(true);            // Make it visible
    this.dispose();                        // Close the current frame (optional)
    }//GEN-LAST:event_RESULT_BUTTON_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROFILE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DASHBOARD_BUTTON_;
    private javax.swing.JRadioButton PROFILE_BUTTON_;
    private javax.swing.JRadioButton RESULT_BUTTON_;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    // End of variables declaration//GEN-END:variables
}
