/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author medal
 */
public class SIGIN extends javax.swing.JFrame {

    /**
     * Creates new form SIGIN
     */
    public SIGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        USER_LABEL_ = new javax.swing.JLabel();
        PASSWORD_LABEL_ = new javax.swing.JLabel();
        USER_TEXTFIELD_ = new java.awt.TextField();
        PASSWORD_TEXTFIELD_ = new java.awt.TextField();
        SIGNIN_BTN_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        USER_LABEL_.setText("USER");

        PASSWORD_LABEL_.setText("PASSWORD");

        USER_TEXTFIELD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER_TEXTFIELD_ActionPerformed(evt);
            }
        });

        PASSWORD_TEXTFIELD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORD_TEXTFIELD_ActionPerformed(evt);
            }
        });

        SIGNIN_BTN_.setText("SIGNIN");
        SIGNIN_BTN_.setToolTipText("");
        SIGNIN_BTN_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGNIN_BTN_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(USER_LABEL_)
                            .addComponent(PASSWORD_LABEL_))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PASSWORD_TEXTFIELD_, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(USER_TEXTFIELD_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(SIGNIN_BTN_)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(USER_LABEL_, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(USER_TEXTFIELD_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PASSWORD_LABEL_)
                    .addComponent(PASSWORD_TEXTFIELD_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(SIGNIN_BTN_)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USER_TEXTFIELD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USER_TEXTFIELD_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USER_TEXTFIELD_ActionPerformed

    private void PASSWORD_TEXTFIELD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORD_TEXTFIELD_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORD_TEXTFIELD_ActionPerformed

    private void SIGNIN_BTN_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGNIN_BTN_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIGNIN_BTN_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PASSWORD_LABEL_;
    private java.awt.TextField PASSWORD_TEXTFIELD_;
    private javax.swing.JButton SIGNIN_BTN_;
    private javax.swing.JLabel USER_LABEL_;
    private java.awt.TextField USER_TEXTFIELD_;
    // End of variables declaration//GEN-END:variables
}
